### ISSUE TITLE
Redirect loop

### ISSUE THREAD

**Issue by jurezove** [dsaronin/milia#42]
Hey

I'm experiencing a redirect loop (even with your sample app on http://sample-milia.herokuapp.com) when following these steps:

1. sign up
2. confirm account and login
3. sign out
4. try to register with the same email (it obviously fails)
5. login

Then, the redirect loop occurs because of the `Milia::Control::InvalidTenantAccess`- I guess the tenant_id stays in the Thread and that causes the invalid_tenant error which causes redirects from index to user's landing page and back.

![screen shot 2014-09-10 at 11 56 19](https://cloud.githubusercontent.com/assets/893398/4215669/124dde9a-38d1-11e4-9217-6e307291ef3b.png)

I suspect we would have to clear `Thread.current[:tenant_id]`somewhere along the way?

**Comment by dsaronin** [comment]
This is now fixed: v1.0.1 (Rails 4.0)
I will also be making corrections to v1.1.1 (Rails 4.1) and soon for v1.2.0 (Rails 4.2)
