### ISSUE TITLE
Is there any way to disable "acts_as_...." in the models all at once?

### ISSUE THREAD

**Issue by GildedHonour** [dsaronin/milia#51]
Is there any way to disable "acts_as_...." in the models all at once?

**Comment by dsaronin** [comment]
no. If this is a requirement you have, you probably shouldn't be trying to
do multi-tenanting.

**Comment by GildedHonour** [comment]
I need to disable it only for testing - when I run the tests, acts_as_ternant gem allows to do that. The only way to disable it now is to comment acts_as in the models, right?

**Comment by dsaronin** [comment]
but there's no need to disable tenanting in tests. The README has
recommendation on how to do test setups in a tenanting mode. you should
test things as close to the actual app as possible, including running your
tests against tenanted model. It does mean that your fixtures will need to
be set up correctly for tenanting. You can also view the sample tests
within the milia gem itself for examples of how to set up.

**Comment by GildedHonour** [comment]
I know. But that's not my app and I have an error http://stackoverflow.com/questions/28823709/unable-to-create-a-simple-model-instance-with-acts-as-tenant

So it's easier for me just to disable it only for tests.

**Comment by dsaronin** [comment]
well, I'm looking at the stackoverflow issue now, and first thing I see is
that you should NOT be trying to manually create a tenant. A new tenant
corresponds to a new admin user creation and there is defined code and
procedure for that which you should follow, even in testing. Specifically:
a tenant is tied to a specific user (the owner or admin) via a join table.
You must use the milia methods, outlined in the documentation for new
tenant creation.

Secondly, "Group" is a poor name for a model and probably conflicts with a
Rails keyword. You should rename your model, as that is probably the source
of the error and the reason that the instance is not being created.  You
shouldn't use names common to Rails. Be more specific, such as, MyappGroup
for the model.

So, if you are trying to create a tenant/group for testing, you should use
fixtures. Again, there are samples in the milia test directory for how to
do that.

**Comment by GildedHonour** [comment]
1) In my case creating ternant by the fabric method and new are exactly the same.
2) That's not the reason because the same thing happens for other models as well, for example, I also have a model called Caregiver which also causes the same error.
3) Fixuter use new and create methods under the hood.

**Comment by dsaronin** [comment]
I think the reason you're having problems is because you're not following
the instructions. Show me a simplified code view of how you're creating a
new tenant so I can figure out the problem. I don't want to have to Wade
through your entire code. Milia works.

**Comment by GildedHonour** [comment]
How can I add it to an existing model?

**Comment by dsaronin** [comment]
I'm sorry but I do not understand your question. The instructions tell in
detail how to ensure that a model is tenanted.

The instructions also suggested beginning with a skeleton app, then adding
everything else in. I would direct your attention again to the
sample-milia-app and the process by which it generates, as described in the
README and also in the tutorial. I think if you follow those steps, you
will see the correct way to have a multi-tenanting application. You will
then know how to change your application to be multi-tenanted.
